#!/bin/sh


EXEC=/bin/aesdsocket

case "$1" in
    start)
        start-stop-daemon -S -n aesdsocket -a "$EXEC" -- -d
        ;;
    stop)
        start-stop-daemon -K -n aesdsocket -a "$EXEC"
        ;;
    *)
    echo "Missing argument.\n\n\tUsage: $0 {start|stop}\n"
    exit 1;
esac
